### ISSUE TITLE
Value assignment

### ISSUE THREAD

**Issue by arkena00** [hrkz/cycle#1]
### Description
Values should not be assignable
***

#### Steps to reproduce
1=2

#### Expected result
error

#### Actual result
2

#### Suggested solution *(Optional)*
Check lhs type

#### Additional comments
I'm so cool

**Comment by hrkz** [comment]
Thanks for signaling the issue.

#### Ideas
I think that the most general solution to this problem without explicit simplification would be to test if there are any symbols on the lhs.
